# Site settings
title: Liber Sun
SEOTitle:  Liber Sun Blog
header-img: img/home-bg-o.jpg
email: sun_liber@126.com
description: "è®¡åˆ’æ€»æ¯”å˜åŒ–å¿« ğŸ‘¾ğŸ‘¾ğŸ‘¾ "
keyword: "blog,æ±¤éŸ©æ–‡,å­™è±å¿—"
url: "https://sunlingzhiliber.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/sunlingzhiliber/sunlingzhiliber.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "æ±¤éŸ©æ–‡,ç‰›é€¼ï¼(ç ´éŸ³)ğŸ’˜ğŸ’˜ğŸ’˜"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: False
# weibo_username:     wanghaodi2011
# zhihu_username:     wanghaodi6
github_username:    sunlingzhiliber
#jianshu_username:   afdfc22584c9
#twitter_username:   wanghaodi




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: wanghaodi

# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: edd8cca69b68ed42a774   #ç”Ÿæˆçš„clientID
  clientSecret: 700310c7a4a23dcb2138fc976e18715ea4fe0ca8  #åŒä¸Š
  repo: sunlingzhiliber.github.io    #ä»“åº“åç§°
  owner: sunlingzhiliber    #githubç”¨æˆ·å
  admin: sunlingzhiliber
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
# ba_track_id: ac9b00dc5cae8816e91176b88f2b1018

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: wanghaodi.top               # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 3              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    #     title: "",
    #     href: "https://wanghaodi.top"
    # }
]
